### ISSUE TITLE
server will not work

### ISSUE THREAD

**Issue by KILILIOLIULULOLOLOOOOOOOLLLLLL** [shylor/miniventure#22]
so i updated the game and went to launch the server but THEN it told me this error

 at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at minicraft.saveload.Load.loadWorld(Load.java:306)
        at minicraft.saveload.Load.<init>(Load.java:83)
        at minicraft.saveload.Load.<init>(Load.java:61)
        at minicraft.core.World.initWorld(World.java:128)
        at minicraft.screen.LoadingDisplay.lambda$new$0(LoadingDisplay.java:29)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ChristofferHolmesland** [comment]
This problem is not relevant for this repository. You probably meant to post it [here](https://github.com/chrisj42/minicraft-plus-revived)
